### ISSUE TITLE
ComputeBuffer<char> Strange result

### ISSUE THREAD

**Issue by parxal** [clSharp/Cloo#10]
Example: (c#)
```
char[] pw_cracked = new char[5];
ComputeBuffer<char> cracked_pw_mem_obj = new ComputeBuffer<char>(context, ComputeMemoryFlags.WriteOnly | ComputeMemoryFlags.CopyHostPointer, pw_cracked);
kernel.SetMemoryArgument(0, cracked_pw_mem_obj);
commands.ReadFromBuffer(cracked_pw_mem_obj, ref pw_cracked, false, eventList);

```
Code Kernel

```
__kernel void vector_add( __global char *cracked_pw) {
  cracked_pw[0] = 'h';
  cracked_pw[1] = 'e';
  cracked_pw[2] = 'l';
  cracked_pw[3] = 'l';
  cracked_pw[4] = '0';
}
```

Not getting "hello" on pw_cracked

**Comment by TillAlex** [comment]
Can you post some more code. From your example it seems that you are not executing your kernel, but only setting the argument. Also if you perform a non blocking read you will have to synchronize before checking the content of the host buffer.

**Comment by parxal** [comment]
Full Code

 try
            {
                char[] pw_cracked = new char[5];
                var kernelCl = File.ReadAllText("kernel.cl");
                ComputePlatform platform = ComputePlatform.Platforms[0];
                ComputeContextPropertyList properties = new ComputeContextPropertyList(platform);
                ComputeContext context = new ComputeContext(platform.Devices, properties, null, IntPtr.Zero);
                ComputeBuffer<char> cracked_pw_mem_obj = new ComputeBuffer<char>(context, ComputeMemoryFlags.WriteOnly | ComputeMemoryFlags.CopyHostPointer, pw_cracked);

                ComputeProgram program = new ComputeProgram(context, kernelCl);
                program.Build(null, null, null, IntPtr.Zero);
                ComputeKernel kernel = program.CreateKernel("vector_add");
                kernel.SetMemoryArgument(0, cracked_pw_mem_obj);
                ComputeEventList eventList = new ComputeEventList();
                ComputeCommandQueue commands = new ComputeCommandQueue(context, context.Devices[0], ComputeCommandQueueFlags.None);
                commands.Execute(kernel, null, new long[] { GLOBAL_ITEM_SIZE }, new long[] { LOCAL_ITEM_SIZE }, eventList);
                commands.ReadFromBuffer(cracked_pw_mem_obj, ref pw_cracked, false, eventList);
                commands.Finish();
                Console.WriteLine("Cracked Password: " + String.Join("", pw_cracked));

                commands.Dispose();

                foreach (ComputeEventBase eventBase in eventList)
                {
                    eventBase.Dispose();
                }

                eventList.Clear();
                kernel.Dispose();
                program.Dispose();
                cracked_pw_mem_obj.Dispose();

            }
            catch (Exception ex)
            {
                Console.WriteLine(ex.Message);
            }
            Console.ReadKey();

**Comment by TillAlex** [comment]
The problem is that char is defined differently in C# and OpenCL:

In C# char is 16 bit: https://docs.microsoft.com/en-us/dotnet/api/system.char?view=netframework-4.8

In OpenCL char is 8 bit: https://www.khronos.org/registry/OpenCL/sdk/1.0/docs/man/xhtml/scalarDataTypes.html

Your code works if you replace char by byte in the host part. After casting the byte array to char the output is correct.

**Comment by parxal** [comment]
Yep! it was that :)

```
byte[] pw_cracked = new byte[maxlen + 1];
ComputeBuffer<byte> cracked_pw_mem_obj = new ComputeBuffer<byte>(context, ComputeMemoryFlags.WriteOnly | ComputeMemoryFlags.CopyHostPointer, pw_cracked);
Console.WriteLine("Cracked Password: " + String.Join("", pw_cracked.Select( p => Convert.ToChar(p))));
```
