### ISSUE TITLE
Cannot find or open the PDB file

### ISSUE THREAD

**Issue by solaaa** [clSharp/Cloo#13]
Hi, 
I met a strange problem:
I successfully ran a Cloo-based demo app. on my PC (see it as pc_1).
Then I copied the whole project to another PC (pc_2) and installed the Intel opencl SDK on pc_2.

When I ran the code to **program.Build(xxx)** on pc_2, it raised exception: **Cloo.BuildProgramFailureComputeException**

And the Debug outputed : 
**".\Intel\Opencl\bin\x64\clang_compile64.dll"  cannot find or open the PDB file
".\Windows\System32\common_clang64.dll"  cannot find or open the PDB file**

Additionally, when the code was running, both pc_1 and pc_2  outputed the following in Debug:
".\Intel\Opencl\bin\x64\tbb\tbb.dll"  cannot find or open the PDB file
".\Intel\Opencl\bin\x64\tbb\tbbmalloc.dll"  cannot find or open the PDB file
".\Intel\Opencl\bin\x64\oclCpuBackend64.dll"  cannot find or open the PDB file
".\Intel\Opencl\bin\x64\__ocl_sval_l9.dll"  cannot find or open the PDB file
However, the pc_1 didn't raise exception.

I have no idea where is wrong on pc_2, plz help me lol

Thanks and Regards!
Solaaa

**Comment by TillAlex** [comment]
It is expected that there are no pdb files for the intel driver dlls. This is not the reason for your exception. 

You should check the build log when BuildProgramFailureComputeExceptions are raised:

`try
{
    program.Build(null, options, null, IntPtr.Zero);
}
catch (BuildProgramFailureComputeException e)
{
    Debug.WriteLine(program.GetBuildLog(program.Devices.First()));
}`
