### ISSUE TITLE
VectorAddExample doesn't work for AMD GPU

### ISSUE THREAD

**Issue by otterrrr** [clSharp/Cloo#17]
tested on my AMD RX 470, it doesn't work with the following message:

> --------------------------------------------------------------------------------
> Running "Vector addition"...
> 
> Cloo.BuildProgramFailureComputeException: OpenCL error code detected: BuildProgramFailure.
>    위치: Cloo.ComputeException.ThrowOnError(ComputeErrorCode errorCode)
>    위치: Cloo.ComputeProgram.Build(ICollection`1 devices, String options, ComputeProgramBuildNotifier notify, IntPtr notifyDataPtr)
>    위치: Clootils.VectorAddExample.Run(ComputeContext context, TextWriter log) 파일 E:\vscode\reference\Cloo\ClootilsNetFull\VectorAddExample.cs:line 102
> 
> "Vector addition" finished.
> -------------------------------------------------------------------------------- 

Here's the result of additional information from program.GetBuildLog():

> 
> C:\Users\otter\AppData\Local\Temp\\OCL20648T1.cl:3:13: error: access qualifier can only be used for pipe and image type
>     global  read_only float* a,
>             ^
> C:\Users\otter\AppData\Local\Temp\\OCL20648T1.cl:4:13: error: access qualifier can only be used for pipe and image type
>     global  read_only float* b,
>             ^
> C:\Users\otter\AppData\Local\Temp\\OCL20648T1.cl:5:12: error: access qualifier can only be used for pipe and image type
>     global write_only float* c )
>            ^
> 3 errors generated.
> 
> error: Clang front-end compilation failed!
> Frontend phase failed compilation.
> Error: Compiling CL to IR
>

**Comment by clSharp** [comment]
Thanks for the catch! Fixed in af46b4e1069a9fa74d3b6f99a8f27e77183fc79f.
